### ISSUE TITLE
Feat: Show transaction in SE38

### ISSUE THREAD

**Issue by Alih-b** [Marc-Bernard-Tools/MBT-Command-Field#10]
### Version

Version: 1.4.2

### Description of the Feature Request

For example:
`?@XD01` or `? CODE XD01` would open `SAPMF02D` in SE38 in display mode.
`?@/UI5/THEME_DESIGNER` or `? CODE /UI5/THEME_DESIGNER` would open method `LAUNCH_THEME_DESIGNER`
of class `/UI5/CL_THEME_TOOL` in display mode.

The reason for this feature is that it will be faster than using SE93 or system status, especially for parameter and OO transactions. This way, it will also be easier to open the program of t-code in a new window (optional).

### Additional Information

I've written a utility method that can do the first part (finding the program behind the t-code).
It can then be passed to function module `RS_TOOL_ACCESS`.

Assuming it is used like other utility methods in `/MBTOOLS/CL_SAP`:
```ABAP
DATA(program) = /mbtools/cl_sap=>get_tcode_program( tcode = 'XD01' ).
CALL FUNCTION 'RS_TOOL_ACCESS'
  EXPORTING
    operation     = 'SHOW'
    object_name   = program
    object_type   = 'PROG'
    in_new_window = 'X'. 
```
Sample tests for different types of transactions:
![image](https://github.com/Marc-Bernard-Tools/MBT-Command-Field/assets/65496394/eb88884a-237b-471e-abd4-1f5692d046f4)
![image](https://github.com/Marc-Bernard-Tools/MBT-Command-Field/assets/65496394/9b97e992-7943-44bc-b7e9-a2177f7c36bf)
![image](https://github.com/Marc-Bernard-Tools/MBT-Command-Field/assets/65496394/7ee57601-145d-4cf5-98c9-8aeca381c2a3)

**Comment by mbtools** [comment]
Nice idea. I will check how to best implement it. 

I want to use `@` for sending a message to a user or maybe even starting a [chat](https://github.com/leo-ls/ZombieChannelChat). Not sure when I will get to that though.

The other idea is to use `?+shortcut` to define a shortcut or bookmark for any other possible command. 

For example, create shortcut with `?+t1 run /isdfps/call_trans`, use it with `?t1`, delete it with `?-t1`.

**Comment by noobcoder6985666** [comment]
Cool!
I also considered `?/isdfps/call_trans`. For Devs mapping _empty_ filter value to se38 would come in handy.

I have some more features in mind. Hopefully, there are enough easy-to-use symbols for the moment.

**Comment by mbtools** [comment]
Give it a try with the regular show command but add a `#` at the end (see #11)
