### ISSUE TITLE
Feat: show code for more types of Parameter transactions

### ISSUE THREAD

**Issue by Alih-b** [Marc-Bernard-Tools/MBT-Command-Field#12]
### Version

Version: 1.4.2

### Description of the Feature Request

Some types of parameter t-codes are not covered,
In case they are assigned to a t-code and not directly linked to the program.

### Additional Information

Currently it works for parameter transactions that are linked to SE38 (calling SE38 with program name in the parameters)
or their `SREPOVARI-REPORTTYPE` is empty (ABAP report).
There are other report types though, and for parameter t-codes that are assigned to transaction, their `REPORTTYPE` is 'TR'.
These t-codes can be handled with `SRT_GET_REPORT_OF_TCODE`.
There are also parameter t-codes that are not considered as ABAP report (they do not exist in `SREPOVARI`) but are assigned to another t-code which is assigned to a report.

I guess there are so many different ways to start a program with transaction parameters, so it might not be possible to always find the program behind the t-code. Many of them are auto generated programs though.

**Comment by mbtools** [comment]
There are indeed many options. Feel free to submit a PR. 

There are pretty strict linting rules. Don't worry, just allow edits on the PR branch. I can then make the necessary changes.

**Comment by mbtools** [comment]
Closed by #13
