### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by larshp** [Marc-Bernard-Tools/MBT-Command-Field#2]
`c_unknown` was removed in https://github.com/Marc-Bernard-Tools/MBT-Base/commit/54f9a97eeb1083125b7411dd232c793109785bfc

but used in https://github.com/Marc-Bernard-Tools/MBT-Command-Field/blob/main/src/%23mbtools%23cl_command__show.clas.abap#L57

**Comment by mbtools** [comment]
Closed by https://github.com/Marc-Bernard-Tools/MBT-Command-Field/commit/189fb6316c69e2d5bd191e2920ee9cd744a26f3b
