### ISSUE TITLE
Bug: Executing long commands with !

### ISSUE THREAD

**Issue by Alih-b** [Marc-Bernard-Tools/MBT-Command-Field#5]
### Version

Version: 1.4.1

### Description of the Bug

When a command is too long, it opens a dialog with POPUP_GET_VALUES. 
It fails when executed using '!' but works when using 'run'."

### Steps To Reproduce

1. Navigate to command-field. 
2. enter `? ! func:zverylongfunctionmodulename.`
3. enter the rest of function name in dialog box.
4. Hit enter.

 

### Additional Information

It is because Fields-VALUE(Table parameter of popup_get_values) is empty when the command starts with '!'.

**Comment by mbtools** [comment]
Unfortunately, this is a SAPGUI feature: Anytime an input field starts with `!`, SAPGUI will ignore the entered value (on any screen). It's mentioned in the [documentation](https://help.sap.com/docs/ABAP_PLATFORM_NEW/bd833c8355f34e96a6e83096b38bf192/d1801c54454211d189710000e8322d00.html#features). The setting can't be changed for `POPUP_GET_VALUES`.

I will try to replace `POPUP_GET_VALUES` with a custom popup which will accept the exclamation mark.

**Comment by mbtools** [comment]
Fixed with v1.4.2
